plugins {
    id 'com.android.application'
}

android {
    namespace 'com.etsa.aicreator'
    compileSdk 35

    defaultConfig {
        applicationId "com.etsa.aicreator"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "0.1"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "com.badlogicgames.gdx:gdx:${gdxVersion}"
    implementation "com.badlogicgames.gdx:gdx-backend-android:${gdxVersion}"
}
